{{- if .Values.secret.generate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.cloudConfig.host }}.username: {{ .Values.secret.username | b64enc | quote }}
  {{ .Values.cloudConfig.host }}.password: {{ .Values.secret.password | b64enc | quote }}
{{- end -}}
