apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cpi-creds
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.vCenter.host }}.username: {{ .Values.vCenter.username }}
  {{ .Values.vCenter.host }}.password: {{ .Values.vCenter.password }}
