apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: {{ .Release.Namespace }}
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = {{ uuidv4 }}
    user = {{ .Values.vCenter.username | quote }}
    password = {{ .Values.vCenter.password | quote }}
    port = {{ .Values.vCenter.port | default "443" | quote }}
    insecure-flag = {{ .Values.vCenter.insecureflag | default "1" | quote }}

    [VirtualCenter {{ .Values.vCenter.host | quote }}]
    datacenters = {{ .Values.vCenter.datacenters | quote }}

    [Workspace]
    server = {{ .Values.vCenter.host | quote }}
    datacenter = {{ .Values.vCenter.datacenter | quote }}
    default-datastore = {{ .Values.vCenter.defaultDatastore | quote }}