{{- if .Values.vCenter.configSecret.generate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vCenter.configSecret.name }}
  namespace: {{ .Release.Namespace }}
data:
  csi-vsphere.conf: {{ tpl .Values.vCenter.configTemplate . | b64enc | quote }}
{{- end -}}
