{{- if .Values.storageClass.enable }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: {{ .Values.storageClass.name | default "vsphere-csi-sc" | quote }}
 annotations:
  storageclass.kubernetes.io/is-default-class: {{ .Values.storageClass.isDefault | quote }}
provisioner: csi.vsphere.vmware.com
parameters:
  {{- if .Values.storageClass.datastoreURL  }}
  datastoreURL: {{ .Values.storageClass.datastoreURL | quote }}
  {{- end }}
  {{- if .Values.storageClass.storagePolicyname }}
  storagepolicyname: {{ .Values.storageClass.storagePolicyname | quote }}
  {{- end }}
{{- end }}
