vCenter:
  host: ""
  datacenters: ""
  port: 443
  insecureFlag: true
  username: ""
  password: ""
  configSecret:
    name: "vsphere-config-secret"
    generate: true
    configTemplate: |
      [Global]
      cluster-id = {{ uuidv4 | quote }}
      user = {{ .Values.vCenter.username | quote }}
      password = {{ .Values.vCenter.password | quote }}
      port = {{ .Values.vCenter.port | quote }}
      insecure-flag = {{ .Values.vCenter.insecureFlag | quote }}

      [VirtualCenter {{ .Values.vCenter.host | quote }}]
      datacenters = {{ .Values.vCenter.datacenters | quote }}

csiMigration:
  enabled: false

storageClass:
  enabled: true
  name: "vsphere-csi-sc"
  isDefault: true
  storagePolicyName: ""
  datastoreURL: ""

nodeSelector: {}
